name: Release

on:
  push:
    tags: 
      - "[0-9]+\\.[0-9]+"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  LayoutVersion: ${{ github.ref_name }}
  GH_DEBUG: 1

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  release:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Build
        run: ./build/build.ps1 ${{ env.LayoutVersion }}

      - name: Zip release
        run: Compress-Archive .\build\msi\* release.zip

      - name: Create release
        run: gh release create --verify-tag ${{ env.LayoutVersion }} release.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

